name: Log All PRs to Wiki Page

on:
  pull_request:
    types: [opened]

jobs:
  log_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Clone Wiki Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Append PR to pr-log.md
        run: |
          FILE="wiki/pr-log.md"
          echo -e "\n---\n" >> $FILE
          echo "## PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}" >> $FILE
          echo "- **Author**: ${{ github.event.pull_request.user.login }}" >> $FILE
          echo "- **Created At**: ${{ github.event.pull_request.created_at }}" >> $FILE
          echo "- **State**: ${{ github.event.pull_request.state }}" >> $FILE
          echo "- **Description**:" >> $FILE
          echo "${{ github.event.pull_request.body || 'No description provided.' }}" >> $FILE
          echo -e "\n---\n" >> $FILE

      - name: Commit and Push to Wiki
        run: |
          cd wiki
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pr-log.md
          git commit -m "Append PR #${{ github.event.pull_request.number }} to pr-log"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
